#!/bin/bash

BATTERY_CHARGING_ICON="battery_charging"
BATTERY_ICON="battery"
BATTERY_LOW_ICON="battery_low"

LOW_TEXT="Low"
LOW_LEVEL=30
CRITICAL_TEXT="Critical"
CRITICAL_LEVEL=10
CHARGING_TEXT="Charging"
DISHARGING_TEXT="Discharging"

