#!/bin/bash

function get_brightness() {
	case "$1" in
		"l")
			echo `brightnessctl -l | grep intel -A 1 | egrep -o '[0-9]+%' | egrep -o '[0-9]+'`%
			;;

		"m")
			echo `ddcutil getvcp 10 | egrep -o "current[^,]+" | egrep -o "[0-9]+"`%
			;;

		*)
			echo "unknown"
			;;
	esac
}
