#!/usr/bin/env bash
# Manage logout with rofi
case $1 in
    suspend)
        sudo /usr/bin/systemctl suspend
        ;;
    lock)
        i3lock_screen
        ;;
    logout)
        i3-nagbar -t warning -m 'Are you sure you  want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'
        ;;
    reboot)
        /usr/bin/systemctl reboot
        ;;
    poweroff)
        /usr/bin/systemctl poweroff
        ;;
    #killuser)
    #    loginctl kill-user $USER
    #    ;;
esac
