#!/bin/sh

BLANK='#00000000'
CLEAR=`xrdb -query | grep primary | cut -f2`'22'
DEFAULT=`xrdb -query | grep primary | cut -f2`
TEXT=`xrdb -query | grep foreground | cut -f2`
KEYPRESS=`xrdb -query | grep foreground | cut -f2`'aa'
WRONG=`xrdb -query | grep urgent | cut -f2`'bb'
VERIFYING=`xrdb -query | grep primary | cut -f2`

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$KEYPRESS      \
--bshl-color=$KEYPRESS       \
\
--blur 5                     \
--clock                      \
--indicator                  \
--radius 120                 \
--ring-width 15              \
--keylayout 2                \
--time-str="%H:%M:%S"        \
--date-str="%A, %m %Y"       \
--verif-text="Verifying"     \
--wrong-text="Wrong"         \
--noinput-text="No input"    

