#!/bin/bash

source /home/stivius/scripts/helpers/get_brightness

type=$1

if [ "$type" = "l" ]; then
	val="$2"
	sudo brightnessctl s $val
	name="Laptop"
else
	direction="$2"
	val="$3"
	ddcutil setvcp 10 $direction $val
	name="Monitor"
fi

level=`get_brightness $type`
polybar-msg hook backlight 1
dunstify -h string:x-dunst-stack-tag:brightness --icon=brightness Brightness "[$name] Level is $level"
