#!/bin/bash

source $HOME/.profile
source $SCRIPTS/helpers/battery_helper

export PATH=$PATH:/usr/local/bin
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

level_file='/tmp/battery_level_notify'

if [ -f "$level_file" ]; then
  read -r notify_level < "$level_file"
fi

function ShowLevelNotification {
	if [ "$notify_level" != "$3" ]; then
		echo $3 > $level_file
		dunstify --icon=$1 --urgency=$2 Battery $3
	fi
}

status=`cat /sys/class/power_supply/AC0/online`
if [ $status = 0 ]; then
	level=`cat /sys/class/power_supply/BAT0/capacity`

	if [ $level -gt $CRITICAL_LEVEL ] && [ $LEVEL -le $LOW_LEVEL ] ; then
		ShowLevelNotification $BATTERY_LOW_ICON normal $LOW_TEXT
	elif [ $level -ge 0 ] && [ $level -le $CRITICAL_LEVEL ] ; then
		ShowLevelNotification $BATTERY_LOW_ICON critical $CRITICAL_TEXT 
	fi
fi
