#!/bin/bash

exec > /home/stivius/udev.out 2>&1 

source /home/stivius/scripts/helpers/authority

setxkbmap -layout us,ru -variant ,, -option grp:alt_shift_toggle -option caps:none
echo 0 | tee /sys/module/hid_apple/parameters/fnmode
