#!/bin/bash

screenshot_icon="screenshot"

case "$1" in

 "f" )
	import -window root png:- | xclip -selection clipboard -t image/png
	dunstify --icon=$screenshot_icon Screenshot "Fullscreen captured"
 ;;

 "w" )
	import -window "$(xdotool getwindowfocus -f)" png:- | xclip -selection clipboard -t image/png
	dunstify --icon=$screenshot_icon Screenshot "Window captured"
 ;;

 "s" )
	import png:- | xclip -selection clipboard -t image/png 
	dunstify --icon=$screenshot_icon Screenshot "Selection captured"
 ;;

esac



