#!/bin/bash

screenshot_icon="screenshot"

case "$1" in

 "f" )
	maim | xclip -selection clipboard -t image/png
	dunstify --icon=$screenshot_icon Screenshot "Fullscreen captured"
 ;;

 "w" )
	maim --window $(xdotool getwindowfocus -f) --capturebackground | xclip -selection clipboard -t image/png
	dunstify --icon=$screenshot_icon Screenshot "Window captured"
 ;;

 "s" )
	maim --select | xclip -selection clipboard -t image/png 
	dunstify --icon=$screenshot_icon Screenshot "Selection captured"
 ;;

esac



