#!/bin/bash

MONITOR=`xrandr | grep -P -o "^HDMI(-1)?-2"`

function HDMIConnected {
  ! xrandr | grep $MONITOR | grep disconnected
}

echo $DISPLAY
echo $XAUTHORITY

if HDMIConnected
then
  xrandr --output $MONITOR --rotate left
fi

sleep 1
i3-msg restart
