#!/bin/bash

MODE="$1"

function show_status() {
  local result=`sudo wg show wg0 | grep wg0`
  echo "result $result"
}

case "$MODE" in
  "on")
    wg-quick up wg0
    show_status
    ;;
  "off")
    wg-quick down wg0
    show_status
    ;;
  *)
    dunstify VPN 'Unknown mode'
    ;;
esac
