#!/bin/bash

MODE="$1"

function show_status() {
  if `wg show wg0` | grep wg
}

case "$MODE" in
  "on")
    wg-quick up wg0
    dunstify VPN 'Enabled'
    ;;
  "off")
    wg-quick down wg0
    dunstify VPN 'Disabled'
    ;;
  *)
    dunstify VPN 'Unknown mode'
    ;;
esac
