#!/bin/bash

type=$1
val=$2

if [ type = "l" ]; then
	sudo brightnessctl s $val
	type="Laptop"
else
	ddcutil setvcp 10 $val
	type="Monitor"
fi

level=`get_brightness $1`
dunstify -h string:x-dunst-stack-tag:brightness --icon=brightness Brightness "[$type] Level is $level"
