#!/bin/bash

type=$1

if [ "$type" = "l" ]; then
	val="$2"
	sudo brightnessctl s $val
	name="Laptop"
else
	direction="$2"
	val="$3"
	ddcutil setvcp 10 $direction $val
	name="Monitor"
fi

get_brightness $type
dunstify -h string:x-dunst-stack-tag:brightness --icon=brightness Brightness "[$name] Level is $brightness"
