#!/bin/bash

source /home/stivius/scripts/helpers/battery_helper

USER=/run/user/1000
export XAUTHORITY=$USER/gdm/Xauthority
export DISPLAY=:1
export PATH=$PATH:/usr/local/bin
export DBUS_SESSION_BUS_ADDRESS=unix:path=$USER/bus 

status_file='/tmp/battery_status_notify'

if [ -f "$status_file" ]; then
  read -r notify_status < "$status_file"
fi

function ShowStatusNotification {
	if [ "$notify_status" != "$2" ]; then
		echo "$2" | sudo -u stivius tee "$status_file"
		sudo -u stivius dunstify --icon=$1 Battery $2
	fi
}

status=`cat /sys/class/power_supply/AC0/online`
if [ $status = 0 ]; then
	level=`cat /sys/class/power_supply/BAT0/capacity`

	if [ $level -gt $LOW_LEVEL ] ; then
		ShowStatusNotification $BATTERY_ICON $DISHARGING_TEXT 
	else
		ShowStatusNotification $BATTERY_LOW_ICON $DISHARGING_TEXT 
	fi
else
	ShowStatusNotification $BATTERY_ICON $CHARGING_TEXT
fi

