#!/bin/bash

exec > /home/stivius/udev.out 2>&1

source /home/stivius/scripts/helpers/battery_helper

USER=/run/user/1000
export XAUTHORITY=$USER/gdm/Xauthority
export DISPLAY=:1
export PATH=$PATH:/usr/local/bin

status_file='/tmp/battery_status_notify'

if [ -f "$status_file" ]; then
  read -r notify_status < "$status_file"
fi

echo "Saved status $notify_status"

function ShowStatusNotification {
	if [ "$notify_status" != "$2" ]; then
		sudo -u stivius echo $2 > $status_file
		DBUS_SESSION_BUS_ADDRESS=unix:path=$USER/bus dunstify --icon=$1 Battery $2
	fi
}

status=`cat /sys/class/power_supply/AC0/online`
echo "Current status $status"
if [ $status = 0 ]; then
	level=`cat /sys/class/power_supply/BAT0/capacity`

	if [ $level -gt $LOW_LEVEL ] ; then
		ShowStatusNotification $BATTERY_ICON $DISHARGING_TEXT 
	else
		ShowStatusNotification $BATTERY_LOW_ICON $DISHARGING_TEXT 
	fi
else
	ShowStatusNotification $BATTERY_ICON $CHARGING_TEXT
fi

