#!/bin/bash

current_date=`date +"%d-%m-%Y %T"`

function IsUnmerged {
  git status | grep unmerged
}

if IsUnmerged
then
  dunstify $(pwd) 'Backup failed: unmerged files'
else
  git add .
  git commit -m "Automatic backup $current_date" 
fi
