#!/bin/bash

function IsUnmerged {
  git status | grep unmerged
}

if IsUnmerged
then
  dunstify
  dunstify Git 'Sync failed: unmerged files'
else
  git add .
  git commit -m "Automatic backup $current_date" 
fi
