#!/bin/bash

function laptop_brightness {
	echo `brightnessctl -l | grep intel -A 1 | egrep -o '[0-9]+%' | egrep -o '[0-9]+'`
}

function monitor_brightness {
	echo `ddcutil getvcp 10 | egrep -o "current[^,]+" | egrep -o "[0-9]+"`
}

case "$1" in
	"l")
		laptop_brightness
	;;

	"m")
		monitor_brightness		
	;;

	*)
		echo "unknown"
	;;
esac
