#!/bin/bash

default_sink=`pulsemixer --list-sources | grep Default | awk -F[,:] '{print $3}'`
mute_status=`pulsemixer --id $default_sink --get-mute`

if [ $mute_status = 0 ]; then
	echo " unmuted"
else
	echo " muted"
fi
