#!/bin/sh
shortcut_file=`ls $SHORTCUTS | rofi -dmenu -i`
if [ -n "$shortcut_file" ]; then
	echo "$shortcut_file"
	if [ "$shortcut_file" != "Vim" ]; then
		cat "$SHORTCUTS/$shortcut_file" | python3 $SCRIPTS/format_shortcuts.py | rofi -dmenu -i
	else
		open_zettelkasten "Notes/Vim\ Notes.md"
	fi
fi
