#!/usr/bin/env bash

dir="$HOME/.config/polybar"
# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use 
# polybar-msg cmd quit

# launch on multiple monitors
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --config="$dir/config.ini" --reload top &
done

echo "Bars launched..."
