#!/bin/bash

project_id=`pomodoro_cli.py --projects | rofi -dmenu -i | awk '{print $1}'`
if [[ ! -z "$project_id" ]]; then
	selected_row=`{ echo "New task"; pomodoro_cli.py --tasks $project_id; } | rofi -dmenu -i`
	if [[ ! -z "$selected_row" ]]; then
		case "$selected_row" in
			"New task")
				task_name=`rofi -dmenu -theme-str 'listview { enabled: false;}'`
				if [[ ! -z "$task_name" ]]; then
					task_id=`pomodoro_cli.py --add-task $project_id $task_name`
				fi
			;;
			*)
				task_id=`echo $selected_row | awk '{print $1}'`
			;;
		esac
		if [[ ! -z "$task_id" ]]; then
			pomodoro_cli.py --start-pomo $task_id
			dunstify "Pomodoro" "Task started"
		fi
	fi
fi
