#!/bin/bash

check_param() {
	if [[ -z "$1" ]]; then
		exit
	fi
}

choose_task() {
	project_id=`pomodoro_cli.py --projects | rofi -dmenu -i | awk '{print $1}'`
	check_param "$project_id"
	selected_row=`{ echo "New task"; pomodoro_cli.py --tasks $project_id; } | rofi -dmenu -i`
	check_param "$selected_row"
	case "$selected_row" in
		"New task")
			task_name=`rofi -dmenu -theme-str 'listview { enabled: false;}'`
			check_param "$task_name"
			task_id=`pomodoro_cli.py --add-task $project_id $task_name`
			;;
		*)
			task_id=`echo $selected_row | awk '{print $1}'`
			;;
	esac
	check_param "$task_id"
	record_id=`pomodoro_cli.py --start-pomo $task_id`
	check_param "$record_id"
	dunstify "Pomodoro" "Task started ($record_id)"
}

ACTION="$1"
PID="$2"
case $ACTION in

	"session" )
		choose_task
		pomodoro_polybar new 1 '祥' 'dunstify "Session finished"; pomodoro_cli.py --end-current-pomo'; pomodoro_polybar update $PID
	;;

	"break" )
		# support for long breaks
		pomodoro_polybar new 5 '' 'dunstify "Break finished; pomodoro_cli.py --end-current-pomo"' ; pomodoro_polybar update $PID
	;;

	"cancel" )
		# cancel current pomo
		pomodoro_polybar cancel ; pomodoro_polybar update $PID
	;;

	"increase" )
		pomodoro_polybar increase 60 || pomodoro_polybar new 1 '祥' 'notify-send -u critical "Timer expired."' ; pomodoro_polybar update $PID
	;;

	"decrease" )
		pomodoro_polybar increase -60 ; pomodoro_polybar update $PID
	;;

esac

