#!/bin/bash

TASK_ID=`pomodoro_start_task`

startPomo() { RECORD_ID=`pomodoro_cli --start-pomo $TASK_ID` }


polybar-timer new 25 '祥' 'notify-send "Session finished"' ; polybar-timer update %pid%

polybar-timer cancel ; polybar-timer update %pid%

polybar-timer new 5 '' 'notify-send "Break finished"' ; polybar-timer update %pid%

polybar-timer increase 60 || polybar-timer new 1 '祥' 'notify-send -u critical "Timer expired."' ; polybar-timer update %pid%

polybar-timer increase -60 ; polybar-timer update %pid%
