#!/bin/bash

exec >> /home/stivius/udev.out 2>&1

export XAUTHORITY=/run/user/1000/gdm/Xauthority
export HOME=/home/stivius
export DISPLAY=:1

setxkbmap -layout us,ru -variant ,, -option grp:alt_shift_toggle -option caps:none
echo "exit code $?"
