#!/bin/bash

export XAUTHORITY=/run/user/1000/gdm/Xauthority
export HOME=/home/stivius
export DISPLAY=:1

setxkbmap -layout us,ru -variant ,, -option grp:alt_shift_toggle -option caps:none
echo 0 | tee /sys/module/hid_apple/parameters/fnmode
