#!/bin/bash 

function display_level {
	val="$1"
	if ((0<=$val && $val<=19))
	then
		echo " $val"
	elif ((20<=$val && $val<=39))
	then
		echo " $val"
	elif ((40<=$val && $val<=59))
	then
		echo " $val"
	elif ((60<=$val && $val<=79))
	then
		echo " $val"
	else
		echo " $val"
	fi
}

function get_display_brightness {
	case "$MONITOR" in
		"eDP"*)
			get_brightness l
		;;

		"HDMI"*)
			get_brightness m
		;;

		*)
			echo "unknown"
		;;
	esac
}

level=`get_display_brightness`
display_level $level

