#!/bin/bash

export XDG_RUNTIME_DIR="/run/user/$(id -u)"

function IsUnmerged {
  git status | grep unmerged
}

if IsUnmerged
then
  dunstify $(pwd) 'Sync failed: unmerged files'
else
  git pull origin master
  if IsUnmerged 
  dunstify $(pwd) 'Sync finished with merged conflict'
fi
