#!/bin/bash

# https://github.com/altdesktop/playerctl/#printing-properties-and-metadata
FORMAT="{{ title }} - {{ artist }}"
STOPPED_FILE=/tmp/polybar_music_stopped
PAUSED_FILE=/tmp/polybar_music_paused
PAUSED_HOOK=2
PLAYING_HOOK=1

create_file() {
	echo > $1
}

delete_file() {
	rm $1 2>/dev/null
}

send_hook() {
	polybar-msg hook music-play-pause 1 1>/dev/null 2>&1
}

send_action() {
	polybar-msg action "$1" 1>/dev/null 2>&1
}

update_playback_status() {
	case $1 in
		$PAUSED_HOOK)
			if [[ ! -f "$PAUSED_FILE" ]]; then
				create_file $PAUSED_FILE
				send_hook 
			fi
			;;
		$PLAYING_HOOK)
			if [[ -f "$PAUSED_FILE" ]]; then
				delete_file $PAUSED_FILE
				send_hook 
			fi
			;;
	esac
}

show_playback_status() {
	playerctl metadata --format "$FORMAT" | head -c 100
}

hide_all() {
	if [[ ! -f "$STOPPED_FILE" ]]; then
		create_file $STOPPED_FILE
		send_action "#music-prev.module_hide"
		send_action "#music.module_hide"
		send_action "#music-play-pause.module_hide"
		send_action "#music-next.module_hide"
	fi
}

show_all() {
	if [[ -f "$STOPPED_FILE" ]]; then
		delete_file $STOPPED_FILE
		send_action "#music-prev.module_show"
		send_action "#music.module_show"
		send_action "#music-play-pause.module_show"
		send_action "#music-next.module_show"
	fi
}

PLAYERCTL_STATUS=$(playerctl status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    STATUS=$PLAYERCTL_STATUS
else
    STATUS="Stopped"
fi

if [ "$STATUS" = "Stopped" ]; then
	hide_all
else
	show_all
	if [ "$STATUS" = "Paused" ]; then
		update_playback_status $PAUSED_HOOK
	else
		update_playback_status $PLAYING_HOOK
	fi
	show_playback_status
fi
