#!/bin/bash

# https://github.com/altdesktop/playerctl/#printing-properties-and-metadata
FORMAT="{{ title }} - {{ artist }}"

update_hooks() {
	polybar-msg hook music-play-pause $1 1>/dev/null 2>&1
}

show_playback_status() {
	playerctl metadata --format "$FORMAT" | head -c 100
}

hide_all() {
	polybar-msg action "module_hide" music-prev
	polybar-msg action "module_hide" music
	polybar-msg action "module_hide" music-play-pause
	polybar-msg action "module_hide" music-next
}

show_all() {
	polybar-msg module_show music-prev
	polybar-msg module_show music
	polybar-msg module_show music-play-pause
	polybar-msg module_show music-next
}

PLAYERCTL_STATUS=$(playerctl status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    STATUS=$PLAYERCTL_STATUS
else
    STATUS="Stopped"
fi

hide_all
if [ "$STATUS" = "Stopped" ]; then
	echo "No music is playing"
else
	if [ "$STATUS" = "Paused"  ]; then
		update_hooks 2
		show_playback_status
	else
		update_hooks 1
		show_playback_status
	fi
fi
