#!/usr/bin/env bash

dir="$HOME/.config/polybar"
# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use 
# polybar-msg cmd quit

# launch on multiple monitors
counter=0
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m MONITOR_NUM=$counter polybar --config="$dir/config.ini" --reload top &
	echo $! > "/tmp/polybar_$counter"
	((counter+=1))
done

echo "Bars launched..."
