[[snippets]]
  description = "Todo.txt - Continuous Today/Overvdue"
  command = "watch -n 5 -c todo.sh view past"
  output = ""

[[snippets]]
  description = "Todo.txt - Continuous Today/Future"
  command = "watch -n 5 -c todo.sh view future"
  output = ""

[[snippets]]
  description = "Todo.txt - Weekly Goals"
  command = "todo.sh ls goals:Weekly | less -R"
  output = ""

[[snippets]]
  description = "Todo.txt - Continuous Weekly Goals"
  command = "watch -n 5 -c todo.sh ls goals:Weekly"
  output = ""

[[snippets]]
  description = "Todo.txt - Monthly Goals"
  command = "todo.sh ls goals:Monthly | less -R"
  output = ""

[[snippets]]
  description = "Todo.txt - Today/Overvdue"
  command = "todo.sh view past | less -R"
  output = ""

[[snippets]]
  description = "Productivity - Monthly Relative"
  command = "unbuffer node index.js report --range-type 3 | less -R"
  output = ""

[[snippets]]
  description = "Productivity - Monthly Absolute"
  command = "unbuffer node index.js report --absolute --range-type 3 | less -R"
  output = ""

[[snippets]]
  description = "Productivity - Weekly Relative"
  command = "unbuffer node index.js report --range-type 2 | less -R"
  output = ""

[[snippets]]
  description = "Productivity - Weekly Absolute"
  command = "unbuffer node index.js report --absolute --range-type 2 | less -R"
  output = ""

[[snippets]]
  description = "xibo cmake build"
  command = "CMAKE_PREFIX_PATH=$HOME/Projects/xibo/xibo-linux/third-party/usr/local/ cmake -Bbuild . && cmake --build build/ --target install -- -j8"
  output = ""

[[snippets]]
  description = "Ledger Balance"
  command = "../ledger/ledger -f transactions.ledger --real --pedantic --explicit bal"
  output = ""
